version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:8080"  # Puerto 80 externo → 8080 interno
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - GIN_MODE=release