name: Deploy Go App to EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH and deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/proyecto
            
            # Pull the latest code
            git fetch origin main
            git reset --hard origin/main
            
            # Create .env if it doesn't exist 
            if [ ! -f .env ]; then
              cp .env.example .env
            fi
            
            # Update .env with secrets
            cat > .env << EOF
            DATABASE_URL="${{ secrets.DATABASE_URL }}"
            PORT=8080
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            EOF
            
            # Stop and clean existing containers
            docker compose down || true
            docker system prune --all --force || true
            docker volume prune --force || true
            
            # Build and start the container (puerto 80:8080)
            docker compose up --build -d
            
            # Wait for container to be ready
            sleep 15
            
            # Verify the container is running
            echo "Checking running containers:"
            docker ps
            
            # Test the application health endpoint on port 80
            echo "Testing application health on port 80:"
            curl -f http://localhost:80/health || echo "Health check failed"